Repository swaraj-das/Collect-your-GamingTools, pull requests merged in 2024-11, with the labels that each got.

#678 Added navbar in contributor's page
  contributor/contributor.html
  contributor/logo.png
Labels: gssoc-ext, level1, hacktoberfest-accepted

#716 Update README.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#729 🛠️ FIX : Broken link on About us page
  aboutus.html
Labels: bug, gssoc-ext, hacktoberfest-accepted

#652 Adding Animations effect in hole Project
  Loader/Loader.css
  aboutus.html
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#712 spacing-between-testimonial-content-and-slide-pagination
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#723 eye icon added
  SignUp/signup.css
  SignUp/signup.html
  login/login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#727 🛠️FIX :Name validation added on contact us section
  index.html
  script.js
Labels: gssoc-ext, level1, hacktoberfest-accepted

#95 Add scroll top button
  index.html
Labels: gssoc-ext, level1

#742 Navbar Z-index and navbar handler issue is solved, Issue number #715
  index.html
  script.js
  style.css
Labels: gssoc-ext, level1
