Repository swaraj-das/Collect-your-GamingTools, pull requests merged in 2024-10, with the labels that each got.

#35 Replaced the old add-to-cart PNG file with a better one.
  images/add.png
Labels: good first issue, gssoc-extd, hacktoberfest

#97 Issue #63 solved. Implemented "Forgot Password" Feature on Login Page.
  login/forgot.css
  login/forgot.html
  login/login.html
Labels: gssoc-extd, level 1, hacktoberfest, hacktoberfest-accepted

#99 Fixed the Navigation issue
  index.html
Labels: gssoc-extd, level 1, hacktoberfest, hacktoberfest-accepted

#108 adding_issue_template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/document.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/refactor_code.yml
  .github/ISSUE_TEMPLATE/task_request.yml
Labels: gssoc-extd, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#109 Update task_request.yml_issue_fix_
  .github/ISSUE_TEMPLATE/task_request.yml
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext

#122 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext

#78 Enhance Add to Cart Button
  index.html
  style.css
Labels: gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#62 Image Quality and positioning Enhanced
  images/chair.png
  images/controller3.png
  images/newchair.png
  images/newcontroller3.png
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#96 Website Footer Updates
  .gitattributes
  index.html
  package-lock.json
  pull_request_template.md
  style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#150 updated the social icon(twitter logo)
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#85 Revamped signup page as asked by you
  SignUp/signup.css
  SignUp/signup.html
  login/login.css
  login/login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#192 ✨added ChatBot (issue#165 solved)✨
  SignUp/signup.css
  SignUp/signup.html
  darkMode.js
  index.html
  login/forgot.css
  login/forgot.html
  login/login.css
  login/login.html
  style.css
Labels: gssoc-ext, Level3, hacktoberfest-accepted

#185 Sidebar for social handles
  index.html
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#206 Added Scroll Progress Bar
  .vscode/settings.json
  index.html
  script.js
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#219 added faq and review with improved css
  index.html
  style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#220 add hover effect in the sidebar social icon
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#234 successfully added the footer section on the login
  login/login.css
  login/login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#186 added functionality to explore button
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#235 Sidebar close button fixed.
  index.html
  script.js
Labels: gssoc-ext, level1, hacktoberfest-accepted

#242 Button interface updated
  SignUp/signup.css
  SignUp/signup.html
  login/forgot.css
  login/forgot.html
  login/login.css
  login/login.html
Labels: enhancement, gssoc-ext, level1, hacktoberfest-accepted

#256 [FIX] Sign up button & made Responsive
  README.md
  SignUp/signup.css
  SignUp/signup.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#268 Improved hover effect of add to cart button
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#308 Fixed Navbar issue !
  style.css
Labels: gssoc-ext, Level3, hacktoberfest-accepted

#307 Updated the twitter logo to new X logo in login page
  login/login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#311 FAQ enhancement
  .vscode/settings.json
  index.html
  script.js
  style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#317 Added the scroll to top button feature with enhanced ui and better functioning.
  index.html
  package-lock.json
  script.js
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#266 Added dockerfile docker-compose.yml
  Dockerfile
  backend/Dockerfile
  docker-compose.yml
Labels: gssoc-ext, Level3, hacktoberfest-accepted

#328 issue327fixed
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#333 Update Sidebar Toggle Functionality and Sidebar position updated
  index.html
  script.js
  style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#344 adding annimation to buttons
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#350 Added Contributor's Page
  Contributors/contributor.css
  Contributors/contributor.html
  Contributors/contributor.js
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#358 Updated meta keywords and description
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#381 Added privacy policy page to the website
  PrivacyPolicy/PrivacyPolicy.css
  PrivacyPolicy/PrivacyPolicy.html
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#392 update: referenced the links to the homepage sections
  login/login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#395 issue #379 solved.
  aboutus.html
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#399 Alignment fixed
  index.html
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#400 Enhanced Testimonial Section By Adding Card Carousel
  images/boy1.png
  images/boy2.png
  images/girl1.png
  images/girl2.png
  index.html
  script.js
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#406 Add: Search bar functionality with smooth page transitions
  index.html
  script.js
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#409 Email format validation added
  SignUp/signup.js
  login/login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#437 Add Translation Tool done ! #397
  aboutus.html
  index.html
  style.css
Labels: gssoc-ext, Level3, hacktoberfest-accepted

#440 Placeholder added
  SignUp/signup.css
  SignUp/signup.html
  login/login.css
  login/login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#424 Using_Reputed_Mail_Services_For_Signup
  SignUp/signup.css
  SignUp/signup.html
  SignUp/signup.js
Labels: gssoc-ext, level1, hacktoberfest-accepted

#455 [BUG] Text Alignment #454
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#474 Updated footer-Bottom
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#441 Added redirections to the icons like facebook,insta,etc
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#478 Update auto-comment-issue.yml
  .github/workflows/auto-comment-issue.yml
Labels: gssoc-ext, hacktoberfest-accepted

#479 Update auto-comment-issue.yml
  .github/workflows/auto-comment-issue.yml
Labels: gssoc-ext, hacktoberfest-accepted

#483 Update workflows issue reminder addition
  .github/workflows/issue reminder.yml
Labels: gssoc-ext, hacktoberfest-accepted

#484 #419 Fix/UI fix
  .vscode/settings.json
  login/1.jpg
  login/login.css
  login/login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#498 Swiper button overlapping removed
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#501 Fixed the darkmode text issue and also fixed the social sidebar of a…
  aboutus.html
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#515 Fix issue #510 Fix issue #510 Added hover effects
  aboutus.html
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#536 Added PrValidator github workflow
  .github/workflows/PRValidator.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#533 added express rate limit
  backend/router/authRoute.js
Labels: gssoc-ext, level1, hacktoberfest-accepted

#549 Successfully youtube icon got responsive with hover and removed twitter duplicates
  aboutus.html
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#562 Update README.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#583 Fix/email placeholder box width
  SECURITY.md
  popup/popup.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#588 Sidebar issue fixed
  aboutus.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#567 Enhanced contrast of testimonial section that matches with the theme of website
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#592 Added Border and Hover Effect to "Contact Our Customer Support Team" …
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#597 Made `email` & `phone no` launchable on clicking link in footer
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#599 BUG: fixed the link to Privacy Policy page on the Pop-Up
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#591 PWA enabled
  images/logo-192x192.png
  images/logo-512x512.png
  index.html
  manifest.json
  script.js
  service-worker.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#504 Add Google Authentication to the Application #340
  index.html
  login/.env
  login/auth.js
  login/login.html
Labels: gssoc-ext, Level3, hacktoberfest-accepted

#594 Added a lottie animation loader to the website
  Loader/Loader.css
  Loader/Loader.js
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#612 Chore: redesign welcome popup box text
  index.html
  popup/popup.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#602 contributor page reworked.
  Contributors/contributor.css
  Contributors/contributor.html
  Contributors/contributor.js
  contributor/contributor.css
  contributor/contributor.html
  contributor/contributor.js
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#642 Completed The Enhancements
  Contributing.md
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted

#656 bug Fixed
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#660 Feature: Redesiged the testimonial section
  style.css
Labels: bug, gssoc-ext, level1, hacktoberfest-accepted

#663 fix: fixed the about us page cards dark mode
  aboutus.html
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#679 update
  index.html
  script.js
Labels: gssoc-ext, level1, hacktoberfest-accepted

#682 Successfully Updated CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#636 added pop animation on product and slide animation on color-box
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#689 ✨Add Visitor Counter feature done !
  index.html
  script.js
  style.css
Labels: gssoc-ext, Level3, hacktoberfest-accepted

#628 Added `Disclaimer Page`
  disclaimer/disclaimer.css
  disclaimer/disclaimer.html
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#688 Adding smoothness to pop back animation for products
  style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#694 Improve Contributors page done ! #650
  contributor/contributor.js
Labels: gssoc-ext, Level3, hacktoberfest-accepted
